#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false

    # MY OWN OPTIONS
    filemanager = "nerdtree"
    vimcompatible = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"   

# enable_neomake = false
# enable_ale = true




# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "checkers"

[[layers]]
  name = 'shell'
  default_position = 'left'
  default_height = 30

[[layers]]
  name = "chinese"

[[layers]]
  name = "lang#c"
  clang_executable = "/usr/bin/clang++"
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "games"

[[layers]]
  name = "debug"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "cscope"

# my own plug
[[custom_plugins]]
    name = "907th/vim-auto-save"
    merged = 0

# tagbar plug
[[custom_plugins]]
    name = "majutsushi/tagbar"
    merged = false
