#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # 设置 SpaceVim 主题及背景，默认的主题是 gruvbox，如果你需要使用更
    # 多的主题，你可以载入 colorscheme 模块
    colorscheme = "gruvbox"
    # 背景可以取值 "dark" 和 "light"
    colorscheme_bg = "dark"
    # 启用/禁用终端真色，在目前大多数终端下都是支持真色的，当然也有
    # 一小部分终端不支持真色，如果你的 SpaceVim 颜色看上去比较怪异
    # 可以禁用终端真色，将下面的值设为 false
    enable_guicolors = true
    # 设置状态栏上分割符号形状，如果字体安装失败，可以将值设为 "nil" 以
    # 禁用分割符号，默认为箭头 "arrow"
    statusline_separator = "nil"
    statusline_separator = "bar"
    # 设置顶部标签列表序号类型，有以下五种类型，分别是 0 - 4
    # 0: 1 ➛ ➊ 
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1
    buffer_index_type = 4
    # 显示/隐藏顶部标签栏上文件类型图标，这一图标需要安装 nerd fonts，
    # 如果未能成功安装这一字体，可以隐藏图标
    enable_tabline_filetype_icon = true
    # 是否在状态栏上显示当前模式，默认情况下，不显示 Normal/Insert 等
    # 字样，只以颜色区分当前模式
    enable_statusline_display_mode = false

    # MY OWN OPTIONS
    filemanager = "nerdtree"
    # vimcompatible = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"   


# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'left'
  default_height = 30

[[layers]]
  name = "lang#c"
  clang_executable = "/usr/bin/clang++"
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"

[[layers]]
  name = "lang#markdown"

# [[layers]]
  # name = "checkers"
  # enable_neomake = false
  # enable_ale = true

[[layers]]
  name = "git"


[[layers]]
  name = "debug"

[[layers]]
  name = "lang#sh"


# my own plug
[[custom_plugins]]
    name = "907th/vim-auto-save"

[[custom_plugins]]
    name = "majutsushi/tagbar"

[[custom_plugins]]
    name = "sjl/gundo.vim"

[[custom_plugins]]
    name = "Yggdroot/LeaderF"
    build = "./install.sh"

[[custom_plugins]]
    name = "SpaceVim/gtags.vim"

[[custom_plugins]]
    name =  "Shougo/vimproc.vim"
    build = "make"

[[custom_plugins]]
    name =  "rdnetto/YCM-Generator"
