#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # 设置 SpaceVim 主题及背景，默认的主题是 gruvbox，如果你需要使用更
    # 多的主题，你可以载入 colorscheme 模块
    colorscheme = "gruvbox"
    # 背景可以取值 "dark" 和 "light"
    colorscheme_bg = "dark"
    # 启用/禁用终端真色，在目前大多数终端下都是支持真色的，当然也有
    # 一小部分终端不支持真色，如果你的 SpaceVim 颜色看上去比较怪异
    # 可以禁用终端真色，将下面的值设为 false
    enable_guicolors = true
    # 设置状态栏上分割符号形状，如果字体安装失败，可以将值设为 "nil" 以
    # 禁用分割符号，默认为箭头 "arrow"
    statusline_separator = "nil"
    statusline_separator = "bar"
    # 设置顶部标签列表序号类型，有以下五种类型，分别是 0 - 4
    # 0: 1 ➛ ➊ 
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1
    buffer_index_type = 4
    # 显示/隐藏顶部标签栏上文件类型图标，这一图标需要安装 nerd fonts，
    # 如果未能成功安装这一字体，可以隐藏图标
    enable_tabline_filetype_icon = true
    # 是否在状态栏上显示当前模式，默认情况下，不显示 Normal/Insert 等
    # 字样，只以颜色区分当前模式
    enable_statusline_display_mode = false

    # MY OWN OPTIONS
    filemanager = "nerdtree"
    # vimcompatible = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"   


# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "lang#latex"

# [[layers]]
  # name = "checkers"
  # show_cursor_error = true
  # lint_on_the_fly = true
  # enable_ale = true


[[layers]]
  name = 'shell'
  default_position = 'left'
  default_height = 30

[[layers]]
  name = "chinese"

[[layers]]
  name = "lang#c"
  clang_executable = "/usr/bin/clang++"
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

# [[layers]]
  # ndfame = "games"

[[layers]]
  name = "debug"

# [[layers]]
  # name = "lang#go"

# 不是使用原因有两个
# 第一，layers 自动携带了gutentags 只有个插件，这一个插件对于Martins.github.io 这一个仓库表现异常
# 第二, 使用四个按键的命令令人无法忍受
# 暂时直接使用gtas.vim
# [[layers]]
  # name = "tags"
  
# [[layers]]
    # name = "denite"

[[layers]]
  name = "lang#sh"

# [[layers]]
  # name = "lang#julia"

# [[layers]]
    # name = "lang#javascript"
    # auto_fix = true
    # enable_flow_syntax = true

# my own plug
[[custom_plugins]]
    name = "907th/vim-auto-save"

[[custom_plugins]]
    name = "majutsushi/tagbar"

[[custom_plugins]]
    name = "sjl/gundo.vim"

# SpaceVim 并没有使用该
[[custom_plugins]]
    name = "Yggdroot/LeaderF"
    build = "./install.sh"

# 使用Gtags 
# 1. 更新操作, 
# 2. 创建操作, 手动创建，对话框的结构
# 3. quickfix window 的设置需要类似于leaderf的效果
# 4. 封装快捷键
# 5. 
[[custom_plugins]]
    name = "SpaceVim/gtags.vim"

# [[custom_plugins]]
    # name = "ludovicchabant/vim-gutentags"
#
# [[custom_plugins]]
    # name = "skywind3000/gutentags_plus"
#
[[custom_plugins]]
    name =  "Shougo/vimproc.vim"
    build = "make"
