session_name: note
windows:
  - window_name: org-mode
    layout: tiled
    shell_command_before:
      - cd ~/core/org-mode
      - nvim
  - window_name: .dotfiles
    layout: tiled
    shell_command_before:
      - cd ~/core/.dotfiles
      - nvim
